export default class BossPanelUI {
    constructor(scene) {
        this.scene = scene;
        this.setupBossListeners();
    }

    setupBossListeners() {
        const closeBtn = document.getElementById('close-boss-btn');
        if (closeBtn) closeBtn.onclick = () => this.closeBossPanel();

        const assignBtn = document.getElementById('assign-boss-task-btn');
        if (assignBtn) assignBtn.onclick = () => this.assignBossTask();

        const input = document.getElementById('boss-task-input');
        if (input) {
            // Prevent Phaser from capturing keys while typing
            input.addEventListener('keydown', (e) => {
                e.stopPropagation();
                if (e.key === 'Enter') this.assignBossTask();
            });
            input.addEventListener('keyup', (e) => e.stopPropagation());
            input.addEventListener('keypress', (e) => e.stopPropagation());
        }

        const deskBoxes = document.querySelectorAll('.desk-box');
        deskBoxes.forEach(box => {
            box.onclick = () => {
                deskBoxes.forEach(b => b.classList.remove('active'));
                box.classList.add('active');
                this.renderDeskDetail(box.dataset.desk);
            };
        });

        // -------------------------------------------------------
        // Received by EMPLOYEES when boss assigns a task.
        // Message format: BOSS_TASK_ASSIGN:deskId:taskId:text
        //   deskId = 'all' | 'd1'..'d6'
        //   taskId = the numeric ID generated by the boss
        //   text   = task description
        // -------------------------------------------------------
        window.handleBossTaskReceived = (deskId, taskId, text) => {
            if (!this.scene.todoManager) return;
            if (deskId === 'all') {
                // taskId is a comma-separated list: "d1=1234,d2=5678,..."
                const pairs = taskId.split(',');
                pairs.forEach(pair => {
                    const [desk, id] = pair.split('=');
                    if (desk && id) {
                        this.scene.todoManager.addTaskWithId(desk, parseFloat(id), text, true);
                    }
                });
            } else {
                this.scene.todoManager.addTaskWithId(deskId, parseFloat(taskId), text, true);
            }
            this.scene.showPopup(`THE BOSS HAS ASSIGNED A NEW TASK! 💡`);
            this.updateDeskNotifications();
            if (this.scene.activeDesk) this.scene.todoUI.renderTodos();
        };

        // -------------------------------------------------------
        // Received by EMPLOYEES when boss removes a boss task.
        // Message format: BOSS_TASK_REMOVE:deskId:taskId
        // -------------------------------------------------------
        window.handleBossTaskRemoved = (deskId, taskId) => {
            if (!this.scene.todoManager) return;
            this.scene.todoManager.deleteTaskByBoss(deskId, parseFloat(taskId));
            this.updateDeskNotifications();
            if (this.scene.activeDesk === deskId) this.scene.todoUI.renderTodos();
        };
    }

    openBossPanel() {
        const overlay = document.getElementById('boss-panel-overlay');
        if (overlay) {
            overlay.style.display = 'flex';
            const list = document.getElementById('boss-detail-list');
            if (list) list.innerHTML = '';
            const title = document.getElementById('detail-title');
            if (title) title.textContent = 'Select a desk to view tasks';
            document.querySelectorAll('.desk-box').forEach(b => b.classList.remove('active'));
            const deskSelect = document.getElementById('boss-desk-select');
            if (deskSelect) deskSelect.value = 'all';
        }
    }

    renderDeskDetail(deskId) {
        const list = document.getElementById('boss-detail-list');
        const title = document.getElementById('detail-title');
        if (!list || !title) return;

        title.textContent = `Tasks for Desk ${deskId.toUpperCase()}`;
        list.innerHTML = '';
        const tasks = this.scene.todoManager.getTasks(deskId);

        if (tasks.length === 0) {
            list.innerHTML = '<li style="color:#666; font-style:italic">No active tasks found</li>';
            return;
        }

        tasks.forEach(t => {
            const li = document.createElement('li');
            li.className = `boss-read-only-item ${t.completed ? 'done' : ''}`;
            li.innerHTML = `
                <span class="status-dot ${t.completed ? 'done' : ''}"></span>
                <span style="flex:1">${t.text}</span>
                <button class="boss-delete-btn" title="Remove this task">&times;</button>
            `;

            const delBtn = li.querySelector('.boss-delete-btn');
            if (delBtn) {
                delBtn.onclick = () => {
                    // Local delete
                    this.scene.todoManager.deleteTaskByBoss(deskId, t.id);
                    // Broadcast delete
                    if (window.sendGlobalMessage) {
                        window.sendGlobalMessage(`BOSS_TASK_REMOVE:${deskId}:${t.id}`);
                    }
                    // Re-render
                    this.renderDeskDetail(deskId);
                    this.updateDeskNotifications();
                    // If the actual todo UI is open for this desk, refresh it too
                    if (this.scene.activeDesk === deskId) {
                        this.scene.todoUI.renderTodos();
                    }
                };
            }
            list.appendChild(li);
        });
    }

    closeBossPanel() {
        const overlay = document.getElementById('boss-panel-overlay');
        if (overlay) overlay.style.display = 'none';
        const input = document.getElementById('boss-task-input');
        if (input) input.value = '';
    }

    assignBossTask() {
        if (this.scene.playerRole !== 'boss') return;
        const input = document.getElementById('boss-task-input');
        const deskSelect = document.getElementById('boss-desk-select');
        if (!input) return;

        const text = input.value.trim();
        if (!text) return;

        const targetDesk = deskSelect ? deskSelect.value : 'all';

        if (targetDesk === 'all') {
            // assignGlobalTask returns [{deskId, taskId}, ...] with boss-generated IDs
            const assignments = this.scene.todoManager.assignGlobalTask(text);
            // Encode as "d1=1234,d2=5678,..."
            const idMap = assignments.map(a => `${a.deskId}=${a.taskId}`).join(',');
            // Format: BOSS_TASK_ASSIGN:all:d1=111,d2=222,...:text
            if (window.sendGlobalMessage) {
                window.sendGlobalMessage(`BOSS_TASK_ASSIGN:all:${idMap}:${text}`);
            }
            this.scene.showPopup('Global Task Assigned to all Desks! 📢');
        } else {
            const task = this.scene.todoManager.addTask(targetDesk, text, true);
            // Format: BOSS_TASK_ASSIGN:d1:1234567:text
            if (window.sendGlobalMessage) {
                window.sendGlobalMessage(`BOSS_TASK_ASSIGN:${targetDesk}:${task.id}:${text}`);
            }
            this.scene.showPopup(`Task Assigned to Desk ${targetDesk.toUpperCase()}! 📌`);
        }

        this.closeBossPanel();
        this.updateDeskNotifications();
        if (this.scene.todoUI) this.scene.todoUI.renderTodos();
    }

    updateDeskNotifications() {
        if (this.scene.deskNotifications) {
            this.scene.deskNotifications.forEach(n => n.destroy());
        }
        this.scene.deskNotifications = [];

        const desks = [
            { id: 'd1', x: 460, y: 100 }, { id: 'd2', x: 580, y: 100 }, { id: 'd3', x: 720, y: 95 },
            { id: 'd4', x: 460, y: 190 }, { id: 'd5', x: 590, y: 195 }, { id: 'd6', x: 715, y: 190 }
        ];

        desks.forEach(d => {
            const hasBossTask = this.scene.todoManager.getTasks(d.id).some(t => t.immutable && !t.completed);
            if (hasBossTask) {
                const bulb = this.scene.add.text(d.x, d.y - 30, '💡', { fontSize: '24px' }).setOrigin(0.5);
                bulb.setDepth(2000);
                this.scene.tweens.add({
                    targets: bulb,
                    y: bulb.y - 5,
                    duration: 1000,
                    yoyo: true,
                    repeat: -1,
                    ease: 'Sine.easeInOut'
                });
                this.scene.deskNotifications.push(bulb);
            }
        });
    }
}
